### ISSUE TITLE
Problem with parameter countVars in function perturbTable

### ISSUE THREAD

**Issue by mancag** [sdcTools/UserSupport#106] opened 2018-11-08 13:49 UTC
**SDC tool used:** cellKey
**Version used:**   0.13.4
**Operating system used:** Windows

---

Dear all,
In issue #103, Tobias mentioned the problem with parameter countVars in function pertrubTable that his colleague noticed, but Tobias couldn't reproduce it.
I tested different counting variables for hypercube 9.2 on our national data:
- vsi, vsi_f, vsi_c: all values are equal to 1
- nihce: all values are equal to 0
- moski: some values are 0, some are 1

The result is that all the counting variables with only zeros or only ones lead to an error in function perturbTable. Only the counting variable with mixed values doesn't lead to an error. 

I put the relevant part of the code (with commented error messages) in the attached file code.txt.
[code.txt](https://github.com/sdcTools/UserSupport/files/2561980/code.txt)

Best,
Manca Golmajer

**Comment by bernhard-da** [comment] 2018-11-08 17:39
hi @mancag 

thx for reporting. but the issue is already fixed in the latest version. with 0.14.0 i can't reproduce. furthermore, i just added some unit-tests for this situation in https://github.com/sdcTools/cellKey/commit/71ca76c539208d56ac5ff234fdf99f4eef6b84d2

**Closed by bernhard-da** 2018-11-08 17:39 UTC
Labels: cellKey, invalid
