### ISSUE TITLE
modular fails with 4 dimensions (TA 4.1.3)

### ISSUE THREAD

**Issue by julienlemasson** [sdcTools/UserSupport#19] opened 2016-08-30 15:40 UTC
**SDC tool used** tau-argus
**Version used:**  4.1.3 // 4.1.1
**Operating system used:** Windows

Hello, 
I'm Julien Lemasson, I work with Maxime Bergeat at Insee (France).
I have an issue with modular (free solver) of the 4.1.3 version of Tau-Argus. 
I tabulate two 3-dimensional tables : 2 hierarchical variables in common + 2 other variables (one in each table)
Number of cells
157_53_5 = 41 605 for table 1
157_53_3 =  24 963 for table 2.

The response variable has no decimals. I use the holding option (but I try without and the issue is the same).
I do linked tables and then launch modular.

With Tau-Argus 4.1.1, that works. It is pretty long (2/3 hours). 
With Tau-Argus 4.1.3 (and 4.1.2 too) that crashed pretty fast (1 minute) and a window tells me that :
![error cover the running table](https://cloud.githubusercontent.com/assets/19969437/18094550/310ed56a-6ed4-11e6-9989-29cf6f32d62f.PNG)

One of the difference on the temporary files is on the CSPlogfile.txt (I join bothCSP log files)
[CSPlogfile - 4.1.3.txt](https://github.com/sdcTools/UserSupport/files/444556/CSPlogfile.-.4.1.3.txt)
[CSPlogfile - 4.1.1.txt](https://github.com/sdcTools/UserSupport/files/444558/CSPlogfile.-.4.1.1.txt)

I don't know what is 

>  ERROR: unknown LP problem status = 1101
>  ERROR: pstat=1101 
> but I guess it is related to the "max time per substable" option. I tried few values : 
> "1" => does not work
> "2" and more => does not work
> "0" => work well on 4.1.3, and comparatively fast (20 minutes)... but the results are not satisfactory, because Hypercube does better here (according to the response value of secondary cases), in less time (44 seconds).
> I wish I could try 10 seconds, or whatever value betwen 0 and 1 minutes, but i don't succeed in using this option, and I don't think it can be.

I try other configurations.
- applicate modular (and optimal too) on only one of the two tables (with 3 dimensions so, including 2 hierarchical), but there, the soft just crash, and the window "error runing the cover table" doesn't even appear.
- applicate modular on one big table with the 4 variables. That does not work at all, the soft just crash in the same lapses of above test.
- applicate modular on the 2 tables, removing the hierarchy on 1 out of 2 hierarchical variable, making the number of cells from 66 568 to 157_48_5+157_48_3= 60 288. That works, it takes 20 minutes.
- applicate modular on the 2 tables, removing the other hierarchy on 1 out of 2 hierarchical variable, making the number of cells from 66 568 to 113_53_5+113_53_3= 47 912. That works, but it seems to be long, I turn off the soft, cause of too long time more than 30 minutes. It uses to crash way more early when it does, so i guess it works.
  These last 2 tests lead me to think that it is not a problem of hrc files in particular, but their accumulation.
- I also change the order of the explanatory variables, but it changes anything.

Anyway, modular uses to work, on others tabulations, but there, on this particular configuration, there is an issue. 

If anyone get an idea of what I did wrong (if I did), or how about work around this problem, I am aware !

Best regards :^), 
Julien

**Comment by ppdewolf** [comment] 2016-09-01 06:19
What solver do you use? Cplex, Xpress or Free solver?
Is it possible to construct a (small) example to reproduce your problem?

**Comment by ppdewolf** [comment] 2016-09-01 06:49
Sorry, I see that you have been using the free solver. 
Could you try with XPress and/or Cplex?
The commercial solvers are much more reliable compared to the free solver. I've experienced some problems with the free solver as well, especially with "larger" problems/tables.

But I would still be interested in a (small) example to reproduce your problem though.

**Comment by julienlemasson** [comment] 2016-09-01 15:10
I just try with Xpress and it works. It tooks 3h20.
It is maybe the free solver that is involved, but it actually works with the 4.1.1. 
By the way, when I launch it and then decide to stop the java.exe via the task manager, I get the same error windows "error running the cover table".

I try to build a small example next week, hoping that I will be able to reproduce the error !

Thx

**Comment by ppdewolf** [comment] 2017-06-12 12:39
Any MWE?

**Comment by ppdewolf** [comment] 2017-11-06 08:49
Closing because no MWE provided.

**Closed by ppdewolf** 2017-11-06 08:49 UTC
Labels: bug, help-wanted, low-priority, question, tau-Argus
