### ISSUE TITLE
Hierarchies in cellKey

### ISSUE THREAD

**Issue by tenderle** [sdcTools/UserSupport#103] opened 2018-11-02 15:32 UTC
**SDC tool used:** cellKey 
**Version used:** 0.14.0  
**Operating system used:** Windows

---

Dear @bernhard-da,

Reinhard, a colleague of mine, is testing and comparing the perturbation output of tauargus and the cellKey-package. (@ppdewolf: Without modifications, we receive different cells when using hierarchies in R and tauargus. On Monday, we will send you a report of the comparison.)

Here are two issues regarding the function `perturbTable(...)` he reported me:
- The argument `countVars=...` only allows 0/1 coded variables. However, it did not allow for variables that only have 1s (or only 0s). Users may be confused and don't know what went wrong. [BUT: I was not able to reproduce this error on version 0.14.0. I can give a try next week on my other desktop where I got the error too and I would open a separate issue if it still exists.] 
- The second issue adresses the argument `dimList`. When specifying the dimList not properly, one receives an error message that may confuse users. Could the error message be adjusted or explain what happened? Here is the issue: If you have a factor variable, you must use the factor levels in the dimList object and not the factor values that refer to the levels. Otherwise (i.e. when using the values), the error reads as follows (do you need an example?):

> Error in c_standardize(inputDims[[i]], input = rawData[[dimVarInd[i]]]) : 
>   c_standardize: elements of 'codesOrig' not listed in 'codesOriginal' or 'dups'!

Regarding the second issue, it seems difficult for users to specify a hierarchy. Our joint colleague from Statistics Finland offered to write guidelines. I will also write an email separately to you and @ppdewolf.

Have a nice weekend,
Tobias

**Comment by bernhard-da** [comment] 2018-11-02 19:18
@tenderle thx for the report.

as for the first issue: i was not able to reproduce either. please make a new issue if you can reproduce with versions `>=0.14.0`

as for the second issue: yes, the error is of course not very useful and should be improved. however, i'd still be interested in the code to you actually were using when running into the error as it is very uncommon to use the values associated with factor levels (`as.numeric(myfactor)`) in R. but i agree, the error should be catched earlier (which needs to be done in sdcTable).

however, some more general thoughts on defining hierarchies: how can this be simplified/improved? perhaps we should provide some examples on how you can use `ck_add_nodes()` in a more flexible way when combined with simple base functions such as `split()`, `strsplit()`, `substring()` or `unique()` instead of calling the function many times for 
each levels of a (complex) hierarchy.

perhaps it would also be helpful to include in cellKey a function that allows (like tau-argus) to define a hierarchy that is given by indices within the levels. a trivial implementation (not really tested, just hacked together in literally two minutes without any error/input checking could be:

```
library(data.tree)
dim_by_position <- function(dim, start_char=c(1,2,4,6)) {
  stopifnot(length(unique(nchar(dim)))==1)
  N <- length(dim)
  tot_lev <- unique(substr(dim, 1, start_char[1]))
  df <- data.frame(path=rep(tot_lev, N), stringsAsFactors=FALSE)  
  for (i in 2:length(start_char)) {
    from <- start_char[i]
    if (i==length(start_char)) {
      to <- nchar(dim)[1]
    } else {
      to <- start_char[i+1]-1
    }
    df$path <- paste0(df$path, "/", substr(dim, from, to))
  } 
  return(FromDataFrameTable(dt, pathName="path"))
}

## example

# level 1: substr(1,1)
# level 2: substr(2,3)
# level 3: substr(4,5)
# level 4: substr(6,7)
inp <- c(
  "0010101","0010102","0010103",
  "0010201","0010202",
  "0010301",
  "0020000",
  "0030000"
)
pos <- c(1,2,4,6) # position at which a new level "starts"
dim <- dim_by_position(inp, start_char = pos)
print(dim)
        levelName
1  0             
2   ¦--01        
3   ¦   ¦--01    
4   ¦   ¦   ¦--01
5   ¦   ¦   ¦--02
6   ¦   ¦   °--03
7   ¦   ¦--02    
8   ¦   ¦   ¦--01
9   ¦   ¦   °--02
10  ¦   °--03    
11  ¦       °--01
12  ¦--02        
13  ¦   °--00    
14  ¦       °--00
15  °--03        
16      °--00    
17          °--00
```
the result of this function is a valid hierarchy that can be (once fed into a list together with other dimensional variables) to `perturbTable()`. we/or any users could also provide "fixed" functions for fixed hierarchies in the census (e.g `ck_dim_nace(country="austria")`. any suggestions?

also: perhaps it would be a good harmonization idea to agree on a common format to specify hierarchies that could easily be used in tau-argus,  sdcTable and cellKey,... the current format (`@@;value`-csv-format) is simple but not very intuitive either. any thoughts from @ppdewolf or anyone else on this?

**Comment by janikat** [comment] 2018-11-05 11:55
Hi, I am the colleague from Statistics Finland. 
I agree that the hierarchy files with @value-csv-format are definitely not intuitive at all. But one can learn: my colleague gave me examples and I did! I think this format is more flexible with the codes one uses and that is why I like it.
I think the levels from microdata option doesn't work right when we have pob_h -type of hierarchy. Only if the hierarchy is recoded adding zeros to get codes equal in lenght it can be used. But this is a potential risk to get the file wrong and either get wrong results or end up with an error message. 
One challenge is to remember that the blanks count and get that part correct in the hrc-files. This is the reason why I offered that the files I have already produced could be used as an example. It is easier to adjust them for the national codes. 
Other challenge is to remember that Tau-Argus needs the "full hierarchy" even if you don't report all levels. This is something that I have only started to think: will the extra hierarchy levels introdure more protection that is initially needed? When using suppression in Tau-Argus, one can use weights to adjust secondary suppression to these values that will not be published anyway but can we do something like that with cell key?

**Comment by olangsrud** [comment] 2018-11-05 13:28
Hi, 
Since the discussion is about creating hierarchy/dimList of the type used in sdcTable you my try the function FindDimLists in the package SSBtools. Then dimLists are automatically created from data. The function is in use in the package easySdcTable.

**Comment by r-tent** [comment] 2018-11-05 15:14
Hello @bernhard-da,

I tested the short but nice code you posted. At first I'd like to mention that there is a little typo in the functions last line:
In the line
    return(FromDataFrameTable(dt, pathName="path"))
the "dt" should actually be a "df".
In addition your code only works for examples where level two starts at the second position, to fix this you should change the line
   tot_lev <- unique(substr(dim, 1, start_char[1]))
to
   tot_lev <- unique(substr(dim, 1, start_char[2]-1)) .
But then again the the first entry of "start_char" is obsolete.

**Comment by tenderle** [comment] 2018-11-05 15:17
@bernhard-da thx 

Yes, such functions may be very helpful to new or unexperienced users. 

Further, some users may already have hierarchy files (see the attached *.hrc-file [geo_m.txt](https://github.com/sdcTools/UserSupport/files/2548960/geo_m.txt); I just changed the file ending from .hrc to .txt). For our tests, @r-tent imported our hrc-files in order to create the dimList object. Here I have a short pseudo code for such a function:

```
fifi_hrc_input <- function(file){

  inp <- read.csv(file = file, header=FALSE, col.names="col", as.is = TRUE)
  hrclevels <- inp$col
  tab <- data.table(levels=c("@",paste0("@",str_extract(hrclevels, "[@]+"))), 
                   codes=c("TOTAL",gsub("@","",hrclevels))
                   )
 tab
}

dim_geo <- fifi_hrc_input("geo_m.txt")
```

@olangsrud thx, I haven't tried it but this seems to be a solution too.

**Comment by bernhard-da** [comment] 2018-11-05 15:33
@tenderle @janikat @olangsrud @r-tent thx for all your comments and fixes (for my quick and dirty and untested code).

some points from me:
- i am currently working on a new R package (probably called `sdcHierarchies`) targeted to inexperienced users. in this package there will be a shiny app where one can dynamically and graphically re-order a hierarchy tree and then export it to the format required as input for `sdcTable` and `cellKey`. probably, i will also make an export method so that `.hrc`-files suitable as input for tau-argus can be created. i hope i can release a first version containing some base methods by the begin of next week. this would be a good place where we could summarize our feedback on what else could be done to facilitate the generation of such hierarchy files

- @olangsrud am i right that `FindDimLists()` ony works if all levels are specified in the input data? so you still have to prepare a complete dataset containing all possible (sub)levels? which is (in my opinion) the most work when you start with a microdata file where you only have the characteristics at the deepest level available.

- the reason why i personally like the "tree-based" approach is that it is possible to dynamically "script" and generate the hierarchy trees and it is rather trivial to import/export it to the `@;level"-based text-format.  we should provide however some convenience functions such as (import, convert, export,..)

**Comment by bernhard-da** [comment] 2018-11-05 15:37
also, in respect to #104, i'd be against having allowing blanks in level-names. the main argument against it, s that it will confuse users. if you have something like
```
print(dim)
        levelName
1  Tot             
2   ¦- a        
3   ¦   ¦--a1
4   ¦- a      
```
where ("a" and "a ") (lines 2 and 4) differ by a blank, it is impossible to distinguish the cells when looking at the table. In fact, in the csv-based hierarchy-files i'd rather force quoting the level-names and removing all leading and trailing blanks of those.

**Comment by olangsrud** [comment] 2018-11-05 15:54
> * am i right that `FindDimLists()` ony works if all levels are specified in the input data? so you still have to prepare a complete dataset containing all possible (sub)levels? which is (in my opinion) the most work when you start with a microdata file where you only have the characteristics at the deepest level available.

Yes, you are right. FindDimLists is for cases where you already have all levels in the data. 
... such as the data created by random.hierarchical.data in package treemap: 
FindDimLists(random.hierarchical.data()[,1:3])

**Comment by r-tent** [comment] 2018-11-06 07:38
@bernhard-da,
in #104 I just reflected what seems to be practically done in tau-Argus and what might be a solution for the Problem I adressed. Yet, looking at your example, I absolutely agree, that blanks seem to be not a good idea. Nevertheless I think it would be quite useful to accept "full length codes" (e.g. in the variable dim of your function dim_by_position) that differ in length, since it is quite cumbersome  to extend codes artificially just to guarantee all codes listed have the same length, even if there is no additional information coded.

**Comment by bernhard-da** [comment] 2018-11-06 08:46
@olangsrud  thx

@r-tent what do you mean by "full length codes"? the ida of `dim_by_position()` is just to mimic tau-argus behaviour in the gui. it would not be too difficult to extend this function so that `start_char` is vectorized (having a custom input for each "code"). however, i think in this case it would be much easier to build the hierarchy using `ck_add_nodes()` and `ck_delete_nodes()` where it is already possible to build an arbitrarily complex hierarchy programatically. the big question is on how to make this "easy" for users which of course depends on the structure/levels of the input. any suggestions are welcome.

**Comment by r-tent** [comment] 2018-11-06 09:15
@bernhard-da,
what you do by using stopifnot(length(unique(nchar(dim)))==1) is to force the user to hand over a list of codes with identical length. The hierarchy by level creator of tau-Argus doesn't do this directly, but delivers some weird results. A simple example I gave in #104 is when you have some data that contain codes like bogus1, bogus2.1 and bogus2.2. Here bogus1 has no subcategory at all while bogus2 would be the root category of bogus2.1 and bogus2.2. Splitting categories at position 6 (or position 2 if you start at the end) would seem natural, so you get

bogus1
bogus2
  |--bogus2.1
  |--bogus2.2

Your code currently permits such da categorization, while tau-Argus would create a hierarchy that looks like

bogu
  |--bogus1
bogus2
  |--bogus2.1
  |--bogus2.2

but using the @-notation and unless you extend the code of bogus1 artificially to bogus1.0 (what's easy in this toy example but might create very long useless encoding otherwise). In this regard I think your code could do better than tau-argus, with some little adjustments. Yet on the other hand to me it looks like you are against this additional functionality, but maybe I'm just mistaken?

**Comment by bernhard-da** [comment] 2018-11-06 10:39
@tenderle 

i just changed the function a bit. it now supports unequal length of inputs and one can specify if full or partial codes should be returned. see below: 

also, i am not where this will end up. i think i will put all level generating features into the new sdcHierarchies packages i am writing and sdcTable and cellKey import from there.  

```
rm(list=ls())
library(data.tree)
library(rlang)
dim_by_position <- function(dim, start_pos, full.names=TRUE) {
  stopifnot(is.character(dim))
  stopifnot(is_scalar_logical(full.names))
  stopifnot(is_integerish(start_pos))
  stopifnot(all(diff(start_pos)>=0))
  
  N <- length(dim)
  
  tot_lev <- unique(substr(dim, 1, (start_pos[2]-1)))
  stopifnot(length(tot_lev)==1)
  df <- data.frame(path=rep(tot_lev, N), stringsAsFactors=FALSE)  
  
  # only total specified
  if (length(start_pos)==2) { 
    return(FromDataFrameTable(df, pathName="path"))
  }
  maxdim <- length(start_pos)-1
  for (i in 2:maxdim) {
    from <- start_pos[i]
    if (i==maxdim) {
      to <- start_pos[i+1]
    } else {
      to <- start_pos[i+1]-1
    }
    
    levs <- substr(dim, from, to)
    ii <- which(levs!="")
    
    if (length(ii)>0) {
      if (full.names==TRUE) {
        df$path[ii] <- paste0(df$path[ii], "/", substr(dim, 1, to)[ii])
      } else {
        df$path[ii] <- paste0(df$path[ii], "/", levs[ii])
      }
    }
  } 
  return(FromDataFrameTable(df, pathName="path"))
}
```

testing:

```
## testing unequal dim-length
dim <- c("bogus","bogus1","bogus2","bogus2.1","bogus2.2")

## total only
start_pos <- c(1,6) 
print(dim_by_position(dim, start_pos=start_pos, full.names=TRUE))
         levelName
  levelName
1     bogus

print(dim_by_position(dim, start_pos=start_pos, full.names=FALSE))
  levelName
1     bogus

## first sublevel
start_pos <- c(1,6,6) 
print(dim_by_position(dim, start_pos=start_pos, full.names=TRUE))
   levelName
1 bogus     
2  ¦--bogus1
3  °--bogus2

print(dim_by_position(dim, start_pos=start_pos, full.names=FALSE))
  levelName
1     bogus
2      ¦--1
3      °--2

## complete
start_pos <- c(1,6,7,8) 
print(dim_by_position(dim, start_pos=start_pos, full.names=TRUE))
         levelName
1 bogus           
2  ¦--bogus1      
3  °--bogus2      
4      ¦--bogus2.1
5      °--bogus2.2

print(dim_by_position(dim, start_pos=start_pos, full.names=FALSE))
1 bogus     
2  ¦--1     
3  °--2     
4      ¦--.1
5      °--.2
```

also, a trivial "convert" function to the "@-level"-format can be easily written (and very much improved :))

```
dim_to_df <- function(inp) {
  stopifnot("Node" %in% class(inp))
  xx <- Traverse(inp)
  codes <- sapply(xx, function(x) x$name)
  levels <- sapply(xx, function(x) x$level)
  ats <- sapply(1:length(levels), function(x) {
    paste(rep("@", levels[x]), collapse="")
  })
  data.frame(levels=ats, codes=codes, stringsAsFactors=FALSE)
}
dim_to_df( dim_by_position(dim, start_pos= c(1,6,7,8) , full.names=TRUE))
  levels    codes
1      @    bogus
2     @@   bogus1
3     @@   bogus2
4    @@@ bogus2.1
5    @@@ bogus2.2
```

any comments/improvements are of course very welcome!

**Comment by tenderle** [comment] 2018-11-06 16:38
@bernhard-da thx for the new function

Based on our discussion, let me first try to summarize the different cases of hierarchical codes that may occur (in the data!):

1. **equal dim length**
We have for example the following code for geography `geo_m <- c("01051",...)`. The first two digits stand for NUTS 1, the third adds the NUTS 2 region and the fourth and fifth digits add the NUTS 3 region. 

2. **unequal dim length**
An example would be year of arrival as defined in the draft regulation ESSC 2016/30/3 EN:
 `yae_h <- c("1.1.1.","1.1.2.",...,"1.4.5.","1.5.",...,"1.9.","2.")`.

Without modifications, I was not able to create the dimlist that I need. Workaround: I added an additional digit (e.g. prefix "0" for Total) at the beginning in both cases. With this augmented prefix and some trial and error, I was able to create the dimlist as supposed. However, the definition of `start_pos=` in the second case was not straighforward to me. In tauargus you can enter the length of the hierarchical breakdowns instead ofentering start positions. We in our SAS routines use the end positions. Maybe we can find a harmonised solution?.

**Testing of your function with ou examples:**
```
## equal dim length
geo_m <- c("01051","01053","01054","01055","01056","01057","01058","01059","01060","01061","01062",
           "02000",
           "03151","03152","03153","03154","03155","03156","03157","03158","03251","03252","03254","03255","03256","03257","03351","03352","03353","03354","03355","03356","03357","03358","03359","03360","03361","03451","03452","03453","03454","03455","03456",
           "10155")
geo_m2 <- paste0("0",geo_m)
start_pos <- c(1,2,4,5,6)

#print(dim_by_position(geo_m, start_pos=start_pos, full.names=TRUE))
print(dim_by_position(geo_m2, start_pos=start_pos, full.names=TRUE))
            levelName
1  0                 
2   ¦--001           
3   ¦   °--0010      
4   ¦       ¦--001051
5   ¦       ¦--001053
6   ¦       ¦--001054
7   ¦       ¦--001055
8   ¦       ¦--001056
9   ¦       ¦--001057
10  ¦       ¦--001058
11  ¦       ¦--001059
12  ¦       ¦--001060
13  ¦       ¦--001061
14  ¦       °--001062
15  ¦--002           
16  ¦   °--0020      
17  ¦       °--002000
18  ¦--003           
19  ¦   ¦--0031      
20  ¦   ¦   ¦--003151
21  ¦   ¦   ¦--003152
22  ¦   ¦   ¦--003153
23  ¦   ¦   ¦--003154
24  ¦   ¦   ¦--003155
25  ¦   ¦   ¦--003156
26  ¦   ¦   ¦--003157
27  ¦   ¦   °--003158
28  ¦   ¦--0032      
29  ¦   ¦   ¦--003251
30  ¦   ¦   ¦--003252
31  ¦   ¦   ¦--003254
32  ¦   ¦   ¦--003255
33  ¦   ¦   ¦--003256
34  ¦   ¦   °--003257
35  ¦   ¦--0033      
36  ¦   ¦   ¦--003351
37  ¦   ¦   ¦--003352
38  ¦   ¦   ¦--003353
39  ¦   ¦   ¦--003354
40  ¦   ¦   ¦--003355
41  ¦   ¦   ¦--003356
42  ¦   ¦   ¦--003357
43  ¦   ¦   ¦--003358
44  ¦   ¦   ¦--003359
45  ¦   ¦   ¦--003360
46  ¦   ¦   °--003361
47  ¦   °--0034      
48  ¦       ¦--003451
49  ¦       ¦--003452
50  ¦       ¦--003453
51  ¦       ¦--003454
52  ¦       ¦--003455
53  ¦       °--003456
54  °--010           
55      °--0101      
56          °--010155
```
(The workaround has the side effect of leading and maybe confusing zeroes.)


```
## unequal dim length
yae_h <- c("1.1.1.",  "1.1.2.",  "1.2.1.",  "1.2.2.",  "1.2.3.",  "1.2.4.",  "1.2.5.",  "1.3.1.",
           "1.3.2.",  "1.3.3.",  "1.3.4.",  "1.3.5.",  "1.4.1.",  "1.4.2.",  "1.4.3.",  "1.4.4.",  "1.4.5.",
           "1.5.",  "1.6.",  "1.7.",  "1.8.",  "1.9.",  "2.",  "3.")
yae_h2 <- paste0("0",yae_h)
start_pos <- c(1,2,4,6,7)
print(dim_by_position(yae_h2, start_pos=start_pos, full.names=TRUE))
             levelName
1  0                  
2   ¦--01.            
3   ¦   ¦--01.1.      
4   ¦   ¦   ¦--01.1.1.
5   ¦   ¦   °--01.1.2.
6   ¦   ¦--01.2.      
7   ¦   ¦   ¦--01.2.1.
8   ¦   ¦   ¦--01.2.2.
9   ¦   ¦   ¦--01.2.3.
10  ¦   ¦   ¦--01.2.4.
11  ¦   ¦   °--01.2.5.
12  ¦   ¦--01.3.      
13  ¦   ¦   ¦--01.3.1.
14  ¦   ¦   ¦--01.3.2.
15  ¦   ¦   ¦--01.3.3.
16  ¦   ¦   ¦--01.3.4.
17  ¦   ¦   °--01.3.5.
18  ¦   ¦--01.4.      
19  ¦   ¦   ¦--01.4.1.
20  ¦   ¦   ¦--01.4.2.
21  ¦   ¦   ¦--01.4.3.
22  ¦   ¦   ¦--01.4.4.
23  ¦   ¦   °--01.4.5.
24  ¦   ¦--01.5.      
25  ¦   ¦--01.6.      
26  ¦   ¦--01.7.      
27  ¦   ¦--01.8.      
28  ¦   °--01.9.      
29  ¦--02.            
30  °--03.            
```

Reinhard (thx to @r-tent) meanwhile slightly modificated your code such that we can better demonstrate you our intention. For example, the breakdown definition will be shorter (see example below). The modificated code is additionally adopted to our SAS approach where we target at the last position (just as an example and for comparisons, but maybe as I wrote above, there may be a harmonised solution, or users can decide what they want to enter: start or end positions or length of breakdowns as in tauargus?). 

**Here is his modificated code:**
```
dim_by_position_2 <- function(dim, end_pos, tot_lev="TOTAL", full.names=TRUE) {
  
  stopifnot(is.character(dim))
  stopifnot(is_scalar_logical(full.names))
  stopifnot(is_integerish(end_pos))
  stopifnot(all(diff(end_pos)>=0))
  
  N <- length(dim)
  df <- data.frame(path=rep(tot_lev, N), stringsAsFactors=FALSE) 
  
  # only total specified
  if (length(end_pos)==2) {
    return(FromDataFrameTable(df, pathName="path"))
  }
  maxdim <- length(end_pos)
  for (i in 1:maxdim) {
    if (i==1) {
      from <- 1
    } else {
      from <- end_pos[i-1]+1
    }
    to <- end_pos[i]
    
    levs <- substr(dim, from, to)
    ii <- which(levs!="")
    
    if (length(ii)>0) {
      if (full.names==TRUE) {
        df$path[ii] <- paste0(df$path[ii], "/", substr(dim, 1, to)[ii])
      } else {
        df$path[ii] <- paste0(df$path[ii], "/", levs[ii])
      }
    }
  }
  return(FromDataFrameTable(df, pathName="path")) }
```


And here are the example (with shorter definitions of the breakdowns and no leading zeroes): 
```
## equal dim length
end_pos <- c(2,4,6)
print(dim_by_position_2(yae_h, end_pos=end_pos, full.names=TRUE))
           levelName
1  TOTAL            
2   ¦--01           
3   ¦   °--010      
4   ¦       ¦--01051
5   ¦       ¦--01053
6   ¦       ¦--01054
7   ¦       ¦--01055
8   ¦       ¦--01056
9   ¦       ¦--01057
10  ¦       ¦--01058
11  ¦       ¦--01059
12  ¦       ¦--01060
13  ¦       ¦--01061
14  ¦       °--01062
15  ¦--02           
16  ¦   °--020      
17  ¦       °--02000
18  ¦--03           
19  ¦   ¦--031      
20  ¦   ¦   ¦--03151
21  ¦   ¦   ¦--03152
22  ¦   ¦   ¦--03153
23  ¦   ¦   ¦--03154
24  ¦   ¦   ¦--03155
25  ¦   ¦   ¦--03156
26  ¦   ¦   ¦--03157
27  ¦   ¦   °--03158
28  ¦   ¦--032      
29  ¦   ¦   ¦--03251
30  ¦   ¦   ¦--03252
31  ¦   ¦   ¦--03254
32  ¦   ¦   ¦--03255
33  ¦   ¦   ¦--03256
34  ¦   ¦   °--03257
35  ¦   ¦--033      
36  ¦   ¦   ¦--03351
37  ¦   ¦   ¦--03352
38  ¦   ¦   ¦--03353
39  ¦   ¦   ¦--03354
40  ¦   ¦   ¦--03355
41  ¦   ¦   ¦--03356
42  ¦   ¦   ¦--03357
43  ¦   ¦   ¦--03358
44  ¦   ¦   ¦--03359
45  ¦   ¦   ¦--03360
46  ¦   ¦   °--03361
47  ¦   °--034      
48  ¦       ¦--03451
49  ¦       ¦--03452
50  ¦       ¦--03453
51  ¦       ¦--03454
52  ¦       ¦--03455
53  ¦       °--03456
54  °--10           
55      °--101      
56          °--10155

## unequal dim length
end_pos <- c(2,3,5)
print(dim_by_position_2(geo_m, end_pos=end_pos, full.names=TRUE))
            levelName
1  TOTAL             
2   ¦--1.            
3   ¦   ¦--1.1.      
4   ¦   ¦   ¦--1.1.1.
5   ¦   ¦   °--1.1.2.
6   ¦   ¦--1.2.      
7   ¦   ¦   ¦--1.2.1.
8   ¦   ¦   ¦--1.2.2.
9   ¦   ¦   ¦--1.2.3.
10  ¦   ¦   ¦--1.2.4.
11  ¦   ¦   °--1.2.5.
12  ¦   ¦--1.3.      
13  ¦   ¦   ¦--1.3.1.
14  ¦   ¦   ¦--1.3.2.
15  ¦   ¦   ¦--1.3.3.
16  ¦   ¦   ¦--1.3.4.
17  ¦   ¦   °--1.3.5.
18  ¦   ¦--1.4.      
19  ¦   ¦   ¦--1.4.1.
20  ¦   ¦   ¦--1.4.2.
21  ¦   ¦   ¦--1.4.3.
22  ¦   ¦   ¦--1.4.4.
23  ¦   ¦   °--1.4.5.
24  ¦   ¦--1.5.      
25  ¦   ¦--1.6.      
26  ¦   ¦--1.7.      
27  ¦   ¦--1.8.      
28  ¦   °--1.9.      
29  ¦--2.            
30  °--3.     
```

**Comment by bernhard-da** [comment] 2018-11-06 23:19
@tenderle @r-tent @janikat 

thx for the examples and the testing and updates. i had expected when writing the functions that the code for the overall total is always contained in the input. 

i just uploaded a first (very rough) version of `sdcHierarchies` [**here**](https://github.com/bernhard-da/sdcHierarchies/). this package contains an updated/combined version of all the information from this issue in function `dim_by_position()`:

- argument `as_df` to specify the return-format (node or hrc-format)
- argument `tot_level` is optional. if `NULL` (default) it is assumed, that the overall total is contained in the input; else it is added
- argument `method`: can be either `len` or `endpos` where the former means that you specify the length of the levels (as in tau-argus) while the latter is basically "endpos" approach. internally i just convert endpos to len for simplicity.

perhaps more interestingly, the package contains two interactive shiny apps:

- `dynHier()`: allows to create/modify a tree-based structure by dragging nodes in a tree, adding, removing and renaming them. the result can be exported.
- `fixedHier(x)`: is a (yet incomplete) wrapper to  `dim_by_position()`

as i wrote in the readme, the package is in its very early stages but what i have in mind for the future is to put all dimension-generating/modifying functionality in there and users can make use of this package in `sdcTable` and `cellKey`. but of course it could also be used standalone.

any contributions (from wording to bugs/features) are very welcome at the [**issue-tracker**](https://github.com/bernhard-da/sdcHierarchies/issues).

**Comment by olangsrud** [comment] 2018-11-07 09:56
@bernhard-da thx for information about sdcHierarchies 

Just to make you aware some of my work that is related.

SSBtools::HierarchyCompute is a function made as a part of a specific problem-solving task  at SSB were my job was to speed up computations (not SDC) originally implemented in VTL. The hierarchies are more general than DimList and coded with to/from. DimList can easily be transformed to to-from coding and thus be input to HierarchyCompute.

The function SmallCountRounding::RoundViaDummy is not made to take hierarchies as input. It is assumed that all codes are contained in the data (similar to FindDimLists). Based on the programming already done within HierarchyCompute it will be relatively easy to make versions of RoundViaDummy that can take DimList as input.

That is, in the future, hierarchies made with sdcHierarchies can be input to more function.

**Comment by ppdewolf** [comment] 2018-11-08 06:54
Just to draw your attention:

There is also a repository [hierarchyFiles.](https://github.com/sdcTools/hierarchyFiles) The intention was to collect (example) hierarchy-files for use in tau-argus and/or sdcTable.

Usually it is much easier to start with an existing hierarchy file and adjust it to your needs.

Unfortunately, so far no files are uploaded 😢

**Comment by bernhard-da** [comment] 2019-03-01 06:09
hi everyone, hi @tenderle @r-tent @janikat

yesterday, my new package [`sdcHierarchies`](https://cran.r-project.org/web/packages/sdcHierarchies/index.html) was uploaded on CRAN. This package allows in a flexible way to create hierarchies and import them from vectors as discussed in this issue [`?hier_compute`](https://bernhard-da.github.io/sdcHierarchies/reference/hier_compute.html). It also allows to "convert" such hierarchies into different format, eg [`hier_export(..., as = "argus")`](https://bernhard-da.github.io/sdcHierarchies/reference/hier_export.html) allows to write hrc-filles for tau argus. The package also comes with a shiny app [`?hier_app`](https://bernhard-da.github.io/sdcHierarchies/reference/hier_app.html) that may be used to create / modify hierarchies, extract the required code to build hierarchies, ....

A [`vignette`](https://bernhard-da.github.io/sdcHierarchies/articles/usage.html) how to use the package as well as the entire documentation can be accessed [**here**](https://bernhard-da.github.io/sdcHierarchies/index.html).

I am closing this issue now. In case you have any feedback, suggestions on the package, please [**let me know.**](https://github.com/bernhard-da/sdcHierarchies/issues).

**Closed by bernhard-da** 2019-03-01 06:09 UTC
Labels: cellKey
