### ISSUE TITLE
2016009 in some cases only zeros in all cells

### ISSUE THREAD

**Issue by rvdlaar8** [sdcTools/UserSupport#10] opened 2016-06-27 08:31 UTC
Version used: 4.1.3
## Windows

After an "error" (for instance when not rounded correctly) then in some cases only zero values in all cells.
After a correct result, and then en 'error', in some cases the old solution returns.

**Comment by ppdewolf** [comment] 2017-11-16 13:43
Cannot reproduce anymore. Is there an MWE?

**Comment by ppdewolf** [comment] 2018-05-14 10:53
Closing because cannot reproduce the error anymore.

**Closed by ppdewolf** 2018-05-14 10:53 UTC
Labels: UI, bug, tau-Argus
