### ISSUE TITLE
Some versions of Tau-Argus don't minimise the sum of suppressed cells when Modular method is used (any more!)

### ISSUE THREAD

**Issue by mancag** [sdcTools/UserSupport#170] opened 2021-09-24 13:01 UTC
**SDC tool used:** Tau-Argus  
**Version used:**  3.5.0 (b27), 4.1.3 (b1), 4.1.4(b1), 4.1.6 (b1), 4.2.0 (b5)
**Operating system used:** Windows

---
Hi!

We recently noticed that Tau-Argus 4.1.3 doesn't work correctly any more: it doesn't minimise the sum of suppressed cells when Modular method is used. After careful inspection we were able to find out that on 15.2.2021 Tau-Argus was still working correctly (i.e. the minimisation was done), but on 17.3.2021 is wasn't working correctly any more. The data, the procedure, the software, the permanent Xpress license for USB dongle, the computer haven't changed during this time (there could only be some automatic updates), but the result did. We also tried changing the system date on the computer to one year ago, but Tau-Argus still wasn't working correctly.

We tested the following versions of Tau-Argus: 3.5.0, 4.1.3, 4.1.4, 4.1.6, 4.2.0. We tested suppression of the same table in all versions, using Modular and HyperCube. We used the Tau-Argus test data (tau_testW.asc) to prepare the table: Region | Var1. Primary protection rule: minimum frequency 1000, p% rule (p=10). The results are (see the file attached):
- For HyperCube, sum of suppressed cells is minimised in all versions of Tau-Argus.
- For Modular, sum of suppressed cells is minimised only in versions 3.5.0 and 4.2.0. In versions 4.1.3, 4.1.4, 4.1.6 is NOT minimised.

Our questions and suggestions are:
1. Do you know why suddenly the Modular method stopped minimising the sum of suppressed cells (why the suppression pattern suddenly changed some time between 15.2.2021 and 17.3.2021)?
2. Is it possible to get Tau-Argus 4.1.3 and 4.1.4 working again as it did before (especially Tau-Argus 4.1.4 is very important to us because a lot of processes are based on it)?
3. We suggest that when preparing new versions of Tau-Argus, the format of input files (asc, rda, tab, arb, bat …) and output files (csv …) is changed only if necessary, because the files are incorporated in different processes and changing them causes a lot of additional work for us.

Thank you very much for your help in advance.
Manca Golmajer (Statistics Slovenia)

[Tau_minimisation.xlsx](https://github.com/sdcTools/UserSupport/files/7225762/Tau_minimisation.xlsx)

**Comment by ppdewolf** [comment] 2021-12-20 14:11
I tested again 4.14, 4.1.5 and 4.1.6, this time with Xpress (dongle) and still got the correct results. So I cannot reproduce the error and thus debugging would be difficult.
Moreover, since the problem seems to be absent in the most recent versions, I will not invest too much time into this.

I will close this issue for now. If you have any feedback concerning your third question, please open a new issue.

**Closed by ppdewolf** 2021-12-20 14:11 UTC
Labels: question, tau-Argus, possible bug
