### ISSUE TITLE
Bugs with tau-Argus 4.1.3

### ISSUE THREAD

**Issue by Lars-ErikAlmberg** [sdcTools/UserSupport#22] opened 2016-11-11 06:57 UTC
SDC tool used: tau-argus
Version used: 4.1.3 
Operating system used: Windows

We have tried the new version at Statistics Sweden and found some bugs.

Interface:
1.	You can´t have Swedish letters (å,ä and ö) in the path to the folder were the files are located.
2.	Specify metadata. If you choose free format the new variables are not saved. You have to click OK and leave. Then if you reenter Specify metadata it works as it should.
3.	Specify tables. If you choose p% the minimum frequency is automaticly included, even if you don´t choose minimum frequency. You notice that when you write a batchfile.
4.	Specify tables. If you choose Zero unsafe tau-Argus include a decimal in the range. Suddenly 10 (for example) becomes 10.0 and then you can´t build a table. If you write a batch file the parameter will be 10.0 and you can´t Open batch process without error.
5.	We also had problems with decimals when reloading a table back into tau-Argus for linked secondary suppression. Tau-Argus said the tables (that it has created) were non additative. I removed the decimals and then it was no problem.

Batch mode:
1.	In batch mode tau-Argus don´t produce a log file into the specified folder.

Best Regards,
Lars-Erik Almberg       Statistics Sweden

**Comment by g3o2** [comment] 2016-11-12 11:43
ad 3) Maybe a bug or a feature. Whenever you apply a sensitivity rule, an underlying frequency rule is attached to it by definition. So whether the frequency rule gets checked or not when you choose p% will not have any significant consequence.

**Comment by Lars-ErikAlmberg** [comment] 2016-11-14 06:44
3) Yes, but in this case we laborated with zero unsafe and it was no different if we specified zero unsafe or not, the cell with only one zero contribution was always unsafe.

**Comment by g3o2** [comment] 2016-11-14 08:59
Would it behave any differently with the dominance rule configured instead of p%?

**Comment by Lars-ErikAlmberg** [comment] 2016-11-14 09:57
It behaves the same with dominance rule. But now I found a way round it. The parameters for the frequency rule mathers even if you don´t choose to include it. If you set the freq to 0 and still not include frequency rule, it works as it should. :)

**Comment by ppdewolf** [comment] 2016-11-15 08:19
It would be easier to discuss the points when they are field as separate issues.
Anyway:
1. This is a known issue, see release notes. We are looking into this.
2. Please make a separate issue.
3. See issue #3. Is solved and will be included in next release.
4. Please make a separate issue. I cannot reproduce this. However, might be related to issue #4 
5. Please make a separate issue. If possible, provide a minimal working example so we can reproduce the error.

1. Please make a separate issue.

**Comment by ppdewolf** [comment] 2016-11-16 15:13
They are now mentioned as separate issues

**Closed by ppdewolf** 2016-11-16 15:13 UTC
